import pandas as pd

def prepro_csv1(file_path):
    df = pd.read_csv(file_path, encoding='euc-kr')
    df_ = df['Conclusion\n'].astype('str').apply(lambda x : x.lower())
    df_.replace(['lobe.'], ['lobe'], regex=True, inplace=True)
    df_.replace(['microangiopathy.'], ['microangiopathy'], regex=True, inplace=True)
    df_.replace(['rt'], ['right'], regex=True, inplace=True)
    df_.replace(['lt'], ['left'], regex=True, inplace=True)
    df_.replace(['left.'], ['left'], regex=True, inplace=True)
    df_.replace(['unremarkable.'], ['unremarkable'], regex=True, inplace=True)
    df_.replace(['bg.'], ['bg'], regex=True, inplace=True)
    df_.replace(['mra.'], ['mra'], regex=True, inplace=True)
    df_.replace(['3.mra'], ['mra'], regex=True, inplace=True)
    df_.replace(['injury.'], ['injury'], regex=True, inplace=True)
    df_.replace(['infarctions.'], ['infarction'], regex=True, inplace=True)
    df_.replace(['infarctions'], ['infarction'], regex=True, inplace=True)
    df_.replace(['atrophy.'], ['atrophy'], regex=True, inplace=True)
    df_.replace(['malformation.'], ['malformation'], regex=True, inplace=True)
    df_.replace(['change.'], ['change'], regex=True, inplace=True)
    df_.replace(['pons.'], ['pons'], regex=True, inplace=True)
    df_.replace(['cerebellum.'], ['cerebellum'], regex=True, inplace=True)
    df_.replace(['metastasis.'], ['metastasis'], regex=True, inplace=True)
    df_.replace(['radiata.'], ['radiata'], regex=True, inplace=True)
    df_.replace(['atrophy.'], ['atrophy'], regex=True, inplace=True)
    df_.replace(['meningioma.'], ['meningioma'], regex=True, inplace=True)
    df_.replace(['meningiomas'], ['meningioma'], regex=True, inplace=True)
    df_.replace(['stenosis.'], ['stenosis'], regex=True, inplace=True)
    df_.replace(['infundibulum.'], ['infundibulum'], regex=True, inplace=True)
    df_.replace(['bifurcation.'], ['bifurcation'], regex=True, inplace=True)
    df_.replace(['sinusitis.'], ['sinusitis'], regex=True, inplace=True)
    return df_, df.pop('AcuteInfarction')

def prepro_csv2(file_path):
    df = pd.read_csv(file_path)
    df_ = df['Conclusion\n'].astype('str').apply(lambda x : x.lower())
    df_.replace(['lobe.'], ['lobe'], regex=True, inplace=True)
    df_.replace(['microangiopathy.'], ['microangiopathy'], regex=True, inplace=True)
    df_.replace(['rt'], ['right'], regex=True, inplace=True)
    df_.replace(['lt'], ['left'], regex=True, inplace=True)
    df_.replace(['left.'], ['left'], regex=True, inplace=True)
    df_.replace(['unremarkable.'], ['unremarkable'], regex=True, inplace=True)
    df_.replace(['bg.'], ['bg'], regex=True, inplace=True)
    df_.replace(['mra.'], ['mra'], regex=True, inplace=True)
    df_.replace(['3.mra'], ['mra'], regex=True, inplace=True)
    df_.replace(['injury.'], ['injury'], regex=True, inplace=True)
    df_.replace(['infarctions.'], ['infarction'], regex=True, inplace=True)
    df_.replace(['infarctions'], ['infarction'], regex=True, inplace=True)
    df_.replace(['atrophy.'], ['atrophy'], regex=True, inplace=True)
    df_.replace(['malformation.'], ['malformation'], regex=True, inplace=True)
    df_.replace(['change.'], ['change'], regex=True, inplace=True)
    df_.replace(['pons.'], ['pons'], regex=True, inplace=True)
    df_.replace(['cerebellum.'], ['cerebellum'], regex=True, inplace=True)
    df_.replace(['metastasis.'], ['metastasis'], regex=True, inplace=True)
    df_.replace(['radiata.'], ['radiata'], regex=True, inplace=True)
    df_.replace(['atrophy.'], ['atrophy'], regex=True, inplace=True)
    df_.replace(['meningioma.'], ['meningioma'], regex=True, inplace=True)
    df_.replace(['meningiomas'], ['meningioma'], regex=True, inplace=True)
    df_.replace(['stenosis.'], ['stenosis'], regex=True, inplace=True)
    df_.replace(['infundibulum.'], ['infundibulum'], regex=True, inplace=True)
    df_.replace(['bifurcation.'], ['bifurcation'], regex=True, inplace=True)
    df_.replace(['sinusitis.'], ['sinusitis'], regex=True, inplace=True)
    return df_, df.pop('AcuteInfarction')
